version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    env_file: ./templatesite/.env
    command: python manage.py runserver
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db